// @flow
import { IdempotencyStore } from './core/IdempotencyStore';
import { createRendererAgentHost } from './RendererAgentHost';

const EXPECTED_PUBLIC_COMMANDS = [
  'agent.capabilities',
  'agent.commands.describe',
  'agent.commands.list',
  'agent.concurrency.capabilities',
  'agent.concurrency.lease.acquire',
  'agent.concurrency.lease.release',
  'agent.concurrency.lease.renew',
  'agent.concurrency.status',
  'build.cancel',
  'build.configuration.apply',
  'build.configuration.inspect',
  'build.result',
  'build.start',
  'build.status',
  'build.targets.list',
  'diagnostics.inspect',
  'docs.read',
  'docs.search',
  'editor.functions.add-behavior',
  'editor.functions.add-or-edit-variable',
  'editor.functions.add-scene-events',
  'editor.functions.call',
  'editor.functions.call-batch',
  'editor.functions.change-behavior-property',
  'editor.functions.change-custom-behavior',
  'editor.functions.change-custom-function',
  'editor.functions.change-custom-object',
  'editor.functions.change-extension-properties',
  'editor.functions.change-gameplay-tests',
  'editor.functions.change-object-properties-effects',
  'editor.functions.change-object-property',
  'editor.functions.change-project-properties-resources',
  'editor.functions.change-scene-properties-layers-effects-groups',
  'editor.functions.create-custom-behavior',
  'editor.functions.create-custom-function',
  'editor.functions.create-custom-object',
  'editor.functions.create-extension',
  'editor.functions.create-object',
  'editor.functions.create-or-replace-object',
  'editor.functions.create-scene',
  'editor.functions.describe',
  'editor.functions.describe-instances',
  'editor.functions.generate-events',
  'editor.functions.get-game-starter-summary',
  'editor.functions.initialize-project',
  'editor.functions.inspect-behavior-properties',
  'editor.functions.inspect-extension',
  'editor.functions.inspect-object-properties',
  'editor.functions.inspect-object-properties-effects',
  'editor.functions.inspect-project-properties-resources',
  'editor.functions.inspect-scene-properties-layers-effects',
  'editor.functions.inspect-variables',
  'editor.functions.list',
  'editor.functions.put-2d-instances',
  'editor.functions.put-3d-instances',
  'editor.functions.read-events-source',
  'editor.functions.read-game-project-json',
  'editor.functions.read-scene-events',
  'editor.functions.remove-behavior',
  'editor.functions.run-gameplay-test',
  'editor.functions.run-script',
  'editor.instances.select',
  'editor.selection.focus',
  'editor.types.behaviors.describe',
  'editor.types.behaviors.list',
  'editor.types.effects.describe',
  'editor.types.effects.list',
  'editor.types.objects.describe',
  'editor.types.objects.list',
  'editor.visual.status',
  'events.apply',
  'events.delete',
  'events.insert',
  'events.instructions.describe',
  'events.instructions.search',
  'events.move',
  'events.nodes.describe',
  'events.nodes.list',
  'events.patch',
  'events.read',
  'events.style.update',
  'events.update',
  'export.html5',
  'extensions.behaviors.create',
  'extensions.behaviors.delete',
  'extensions.behaviors.inspect',
  'extensions.behaviors.list',
  'extensions.behaviors.rename',
  'extensions.behaviors.update',
  'extensions.catalog.describe',
  'extensions.catalog.search',
  'extensions.functions.create',
  'extensions.functions.delete',
  'extensions.functions.inspect',
  'extensions.functions.list',
  'extensions.functions.parameters.create',
  'extensions.functions.parameters.delete',
  'extensions.functions.parameters.move',
  'extensions.functions.parameters.rename',
  'extensions.functions.parameters.update',
  'extensions.functions.rename',
  'extensions.functions.update',
  'extensions.install',
  'extensions.installed.inspect',
  'extensions.installed.list',
  'extensions.objects.create',
  'extensions.objects.delete',
  'extensions.objects.inspect',
  'extensions.objects.list',
  'extensions.objects.rename',
  'extensions.objects.update',
  'extensions.objects.variants.create',
  'extensions.objects.variants.delete',
  'extensions.objects.variants.inspect',
  'extensions.objects.variants.list',
  'extensions.objects.variants.move',
  'extensions.objects.variants.rename',
  'extensions.objects.variants.update',
  'extensions.project.create',
  'extensions.project.delete',
  'extensions.project.inspect',
  'extensions.project.list',
  'extensions.project.rename',
  'extensions.remove',
  'extensions.update',
  'external-events.create',
  'external-events.delete',
  'external-events.duplicate',
  'external-events.inspect',
  'external-events.list',
  'external-events.rename',
  'external-events.reorder',
  'external-events.update',
  'external-events.usages',
  'external-layouts.create',
  'external-layouts.delete',
  'external-layouts.duplicate',
  'external-layouts.inspect',
  'external-layouts.instances.create',
  'external-layouts.instances.delete',
  'external-layouts.instances.list',
  'external-layouts.instances.update',
  'external-layouts.list',
  'external-layouts.rename',
  'external-layouts.update',
  'objects.behaviors.add',
  'objects.behaviors.available',
  'objects.behaviors.describe',
  'objects.behaviors.list',
  'objects.behaviors.remove',
  'objects.behaviors.update',
  'objects.definitions.create',
  'objects.definitions.delete',
  'objects.definitions.duplicate',
  'objects.definitions.get',
  'objects.definitions.list',
  'objects.definitions.move-scope',
  'objects.definitions.rename',
  'objects.definitions.usages',
  'objects.groups.create',
  'objects.groups.delete',
  'objects.groups.for-object',
  'objects.groups.get',
  'objects.groups.list',
  'objects.groups.members.add',
  'objects.groups.members.move',
  'objects.groups.members.remove',
  'objects.groups.rename',
  'objects.groups.usages',
  'objects.properties.describe',
  'objects.properties.set',
  'objects.sprite.animations.create',
  'objects.sprite.animations.delete',
  'objects.sprite.animations.get',
  'objects.sprite.animations.list',
  'objects.sprite.animations.move',
  'objects.sprite.animations.update',
  'objects.sprite.collision-mask.set',
  'objects.sprite.frames.add',
  'objects.sprite.frames.delete',
  'objects.sprite.frames.move',
  'objects.sprite.frames.update',
  'objects.sprite.points.delete',
  'objects.sprite.points.set',
  'objects.structure.apply',
  'objects.structure.capabilities',
  'objects.structure.inspect',
  'preview.close-all',
  'preview.control',
  'preview.hot-reload',
  'preview.start',
  'preview.status',
  'project.close',
  'project.create',
  'project.open',
  'project.persistence.status',
  'project.persistence.verify',
  'project.reload',
  'project.save',
  'project.save-as',
  'project.scenes.create',
  'project.scenes.delete',
  'project.scenes.duplicate',
  'project.scenes.get',
  'project.scenes.list',
  'project.scenes.rename',
  'project.scenes.reorder',
  'project.scenes.usages',
  'project.status',
  'publication.integrations.list',
  'publication.prepare',
  'publication.publish',
  'resources.audio.transform',
  'resources.image.slice-spritesheet',
  'resources.image.transform',
  'resources.import-local',
  'resources.import-url',
  'resources.inspect',
  'resources.list',
  'resources.packaging.inspect',
  'resources.processing.capabilities',
  'resources.remove',
  'resources.rename',
  'resources.replace-local',
  'resources.replace-url',
  'resources.text.create',
  'resources.text.read',
  'resources.text.update',
  'resources.visual.delete',
  'resources.visual.import',
  'resources.visual.inspect',
  'resources.visual.relocate',
  'resources.visual.replace',
  'runtime.assert',
  'runtime.debugger.capabilities',
  'runtime.event-trace.capture',
  'runtime.inspect',
  'runtime.logs',
  'runtime.profile.run',
  'runtime.profiler.start',
  'runtime.profiler.status',
  'runtime.profiler.stop',
  'runtime.snapshot',
  'runtime.status',
  'runtime.time.advance',
  'runtime.time.pause',
  'runtime.time.resume',
  'runtime.time.set-scale',
  'runtime.time.status',
  'runtime.time.step',
  'runtime.time.wait-until',
  'runtime.wait-for',
  'safety.checkpoints.create',
  'safety.checkpoints.delete',
  'safety.checkpoints.diff',
  'safety.checkpoints.list',
  'safety.checkpoints.restore',
  'safety.transactions.begin',
  'safety.transactions.commit',
  'safety.transactions.rollback',
  'safety.transactions.status',
  'scene.instances.bulk-delete',
  'scene.instances.bulk-update',
  'scene.instances.create',
  'scene.instances.delete',
  'scene.instances.diagnose-duplicates',
  'scene.instances.duplicate',
  'scene.instances.get',
  'scene.instances.list',
  'scene.instances.move-layer',
  'scene.instances.set-render-order',
  'scene.instances.transform',
  'scene.instances.update',
  'scene.layers.create',
  'scene.layers.delete',
  'scene.layers.list',
  'scene.layers.rename',
  'scene.layers.reorder',
  'scene.open',
  'scene.render.compare',
  'store.objects.import',
  'store.objects.inspect',
  'store.objects.search',
  'store.resources.import',
  'store.resources.inspect',
  'store.resources.search',
  'target.status',
  'validation.run',
];

describe('RendererAgentHost public command inventory', () => {
  it('keeps the complete public registry explicit and deterministic', () => {
    const host = createRendererAgentHost({
      environment: {},
      assetTools: {},
      diagnosticsTools: {},
      editorFunctionService: { run: jest.fn() },
      editorVisualService: {},
      eventTools: {},
      externalProjectItemsService: {},
      sceneLifecycleService: {},
      extensionAuthoringService: {},
      extensionLifecycleService: {},
      objectStructureService: {},
      objectPropertyService: {},
      metadataDiscoveryService: {},
      buildService: {},
      publicationService: {},
      exportService: {},
      previewService: {},
      projectLifecycleService: {},
      runtimeTelemetry: {},
      runtimeDiagnosticsService: {},
      safetyService: {},
      validationService: {},
    });

    const commandNames = host.listCommands().map(command => command.name);
    expect(commandNames).toEqual(EXPECTED_PUBLIC_COMMANDS);
    expect(new Set(commandNames).size).toBe(commandNames.length);
  });

  it('wraps objects.properties.set with project revision and active transaction metadata', async () => {
    let revision = 0;
    const projectRevisionTracker = {
      synchronize: jest.fn(() => revision),
      markMutation: jest.fn(() => {
        revision += 1;
        return revision;
      }),
    };
    const identity = {
      clientId: 'dx24-client',
      agentId: 'GDevelop-Properties-A1',
      sessionId: 'dx24-session',
      taskId: 'dx24-task',
      ownerKey: 'GDevelop-Properties-A1::dx24-session',
    };
    const set = jest.fn(async input => ({
      updated: true,
      applied: input.changes,
    }));
    const host = createRendererAgentHost({
      environment: {
        project: {},
        projectRevisionTracker,
        getTransactionStatus: () => ({
          active: true,
          transactionId: 'tx-dx24-properties',
          owner: identity,
          purpose: 'typed property mutation',
          startedAt: 1,
        }),
      },
      assetTools: {},
      diagnosticsTools: {},
      editorFunctionService: { run: jest.fn() },
      editorVisualService: {},
      eventTools: {},
      externalProjectItemsService: {},
      sceneLifecycleService: {},
      extensionAuthoringService: {},
      extensionLifecycleService: {},
      objectStructureService: {},
      objectPropertyService: { describe: jest.fn(), set },
      metadataDiscoveryService: {},
      buildService: {},
      publicationService: {},
      exportService: {},
      previewService: {},
      projectLifecycleService: {},
      runtimeTelemetry: {},
      runtimeDiagnosticsService: {},
      safetyService: {},
      validationService: {},
    });

    const result = await host.execute(
      'objects.properties.set',
      {
        targetKind: 'object-definition',
        sceneName: 'Game',
        objectName: 'Label',
        changes: [{ path: 'configuration.text', value: 'After' }],
      },
      {
        expectedRevision: 0,
        identity,
        traceId: 'dx24-properties-transaction',
      }
    );

    expect(set).toHaveBeenCalledTimes(1);
    expect(result).toMatchObject({
      command: 'objects.properties.set',
      data: {
        updated: true,
        applied: [{ path: 'configuration.text', value: 'After' }],
      },
      meta: {
        traceId: 'dx24-properties-transaction',
        readOnly: false,
        modifiesProject: true,
        projectRevision: 1,
        transactionId: 'tx-dx24-properties',
      },
    });
    expect(projectRevisionTracker.markMutation).toHaveBeenCalledTimes(1);
  });

  it('preserves idempotent mutation replay when the renderer host is recreated', async () => {
    let revision = 0;
    const projectRevisionTracker = {
      synchronize: jest.fn(() => revision),
      markMutation: jest.fn(() => {
        revision += 1;
        return revision;
      }),
    };
    const idempotencyStore = new IdempotencyStore();
    const run = jest.fn(async () => ({
      results: [{ status: 'finished', success: true, output: {} }],
      didModifyProject: true,
    }));
    const makeHost = () =>
      createRendererAgentHost({
        environment: { project: {}, projectRevisionTracker },
        idempotencyStore,
        assetTools: {},
        diagnosticsTools: {},
        editorFunctionService: { run },
        editorVisualService: {},
        eventTools: {},
        externalProjectItemsService: {},
        sceneLifecycleService: {},
        extensionAuthoringService: {},
        extensionLifecycleService: {},
        objectStructureService: {},
        objectPropertyService: {},
        metadataDiscoveryService: {},
        documentationService: {},
        storeService: {},
        remoteResourceService: {},
        assetProcessingService: {},
        buildService: {},
        publicationService: {},
        exportService: {},
        previewService: {},
        projectLifecycleService: {},
        runtimeTelemetry: {},
        runtimeDiagnosticsService: {},
        safetyService: {},
        validationService: {},
      });

    const input = { extension_name: 'ReplaySafeExtension' };
    const requestContext = {
      expectedRevision: 0,
      idempotencyKey: 'renderer-host-recreation-replay',
    };
    const first = await makeHost().execute(
      'editor.functions.create-extension',
      input,
      requestContext
    );
    const replay = await makeHost().execute(
      'editor.functions.create-extension',
      input,
      requestContext
    );

    expect(run).toHaveBeenCalledTimes(1);
    expect(first.meta.projectRevision).toBe(1);
    expect(replay.meta.projectRevision).toBe(1);
    expect(replay.meta.idempotencyReplayed).toBe(true);
  });
});
