// @flow
import { createRendererAgentHost } from './RendererAgentHost';

const EXPECTED_PUBLIC_COMMANDS = [
  'agent.capabilities',
  'agent.commands.describe',
  'agent.commands.list',
  'diagnostics.inspect',
  'docs.read',
  'docs.search',
  'editor.functions.add-behavior',
  'editor.functions.add-or-edit-variable',
  'editor.functions.add-scene-events',
  'editor.functions.call',
  'editor.functions.call-batch',
  'editor.functions.change-behavior-property',
  'editor.functions.change-gameplay-tests',
  'editor.functions.change-object-properties-effects',
  'editor.functions.change-object-property',
  'editor.functions.change-project-properties-resources',
  'editor.functions.change-scene-properties-layers-effects-groups',
  'editor.functions.create-object',
  'editor.functions.create-or-replace-object',
  'editor.functions.create-scene',
  'editor.functions.describe',
  'editor.functions.describe-instances',
  'editor.functions.generate-events',
  'editor.functions.get-game-starter-summary',
  'editor.functions.initialize-project',
  'editor.functions.inspect-behavior-properties',
  'editor.functions.inspect-object-properties',
  'editor.functions.inspect-object-properties-effects',
  'editor.functions.inspect-project-properties-resources',
  'editor.functions.inspect-scene-properties-layers-effects',
  'editor.functions.inspect-variables',
  'editor.functions.list',
  'editor.functions.put-2d-instances',
  'editor.functions.put-3d-instances',
  'editor.functions.read-events-source',
  'editor.functions.read-game-project-json',
  'editor.functions.read-scene-events',
  'editor.functions.remove-behavior',
  'editor.functions.run-gameplay-test',
  'editor.functions.run-script',
  'editor.instances.select',
  'editor.selection.focus',
  'editor.types.behaviors.describe',
  'editor.types.behaviors.list',
  'editor.types.effects.describe',
  'editor.types.effects.list',
  'editor.types.objects.describe',
  'editor.types.objects.list',
  'editor.visual.status',
  'events.apply',
  'events.delete',
  'events.insert',
  'events.instructions.describe',
  'events.instructions.search',
  'events.move',
  'events.read',
  'events.update',
  'export.html5',
  'extensions.behaviors.create',
  'extensions.behaviors.delete',
  'extensions.behaviors.inspect',
  'extensions.behaviors.list',
  'extensions.behaviors.rename',
  'extensions.behaviors.update',
  'extensions.catalog.describe',
  'extensions.catalog.search',
  'extensions.functions.create',
  'extensions.functions.delete',
  'extensions.functions.inspect',
  'extensions.functions.list',
  'extensions.functions.parameters.create',
  'extensions.functions.parameters.delete',
  'extensions.functions.parameters.move',
  'extensions.functions.parameters.rename',
  'extensions.functions.parameters.update',
  'extensions.functions.rename',
  'extensions.functions.update',
  'extensions.install',
  'extensions.installed.inspect',
  'extensions.installed.list',
  'extensions.objects.create',
  'extensions.objects.delete',
  'extensions.objects.inspect',
  'extensions.objects.list',
  'extensions.objects.rename',
  'extensions.objects.update',
  'extensions.objects.variants.create',
  'extensions.objects.variants.delete',
  'extensions.objects.variants.inspect',
  'extensions.objects.variants.list',
  'extensions.objects.variants.move',
  'extensions.objects.variants.rename',
  'extensions.objects.variants.update',
  'extensions.project.create',
  'extensions.project.delete',
  'extensions.project.inspect',
  'extensions.project.list',
  'extensions.project.rename',
  'extensions.remove',
  'extensions.update',
  'external-events.create',
  'external-events.delete',
  'external-events.inspect',
  'external-events.list',
  'external-events.rename',
  'external-events.update',
  'external-layouts.create',
  'external-layouts.delete',
  'external-layouts.duplicate',
  'external-layouts.inspect',
  'external-layouts.instances.create',
  'external-layouts.instances.delete',
  'external-layouts.instances.list',
  'external-layouts.instances.update',
  'external-layouts.list',
  'external-layouts.rename',
  'external-layouts.update',
  'objects.structure.apply',
  'objects.structure.capabilities',
  'objects.structure.inspect',
  'preview.close-all',
  'preview.control',
  'preview.hot-reload',
  'preview.start',
  'preview.status',
  'project.close',
  'project.create',
  'project.open',
  'project.save',
  'project.save-as',
  'project.status',
  'resources.import-local',
  'resources.inspect',
  'resources.list',
  'resources.remove',
  'resources.rename',
  'resources.replace-local',
  'runtime.assert',
  'runtime.logs',
  'runtime.snapshot',
  'runtime.status',
  'runtime.wait-for',
  'safety.checkpoints.create',
  'safety.checkpoints.delete',
  'safety.checkpoints.diff',
  'safety.checkpoints.list',
  'safety.checkpoints.restore',
  'safety.transactions.begin',
  'safety.transactions.commit',
  'safety.transactions.rollback',
  'safety.transactions.status',
  'scene.open',
  'store.objects.import',
  'store.objects.inspect',
  'store.objects.search',
  'store.resources.import',
  'store.resources.inspect',
  'store.resources.search',
  'validation.run',
];

describe('RendererAgentHost public command inventory', () => {
  it('keeps the complete public registry explicit and deterministic', () => {
    const host = createRendererAgentHost({
      environment: {},
      assetTools: {},
      diagnosticsTools: {},
      editorFunctionService: { run: jest.fn() },
      editorVisualService: {},
      eventTools: {},
      externalProjectItemsService: {},
      extensionAuthoringService: {},
      extensionLifecycleService: {},
      objectStructureService: {},
      metadataDiscoveryService: {},
      exportService: {},
      previewService: {},
      projectLifecycleService: {},
      runtimeTelemetry: {},
      safetyService: {},
      validationService: {},
    });

    const commandNames = host.listCommands().map(command => command.name);
    expect(commandNames).toEqual(EXPECTED_PUBLIC_COMMANDS);
    expect(new Set(commandNames).size).toBe(commandNames.length);
  });
});
